import fs from 'fs';import path from 'path';import {minify} from 'html-minifier-terser';import CleanCSS from 'clean-css';import JavaScriptObfuscator from 'javascript-obfuscator';
const root=process.cwd(),out=path.join(root,'dist');fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(path.join(out,'assets/css'),{recursive:true});fs.mkdirSync(path.join(out,'assets/js'),{recursive:true});fs.cpSync(path.join(root,'assets/images'),path.join(out,'assets/images'),{recursive:true});
const minHtml=async s=>minify(s,{collapseWhitespace:true,removeComments:true,removeRedundantAttributes:true,minifyCSS:true,minifyJS:true});
for(const name of ['index.html','lekh.html']){const src=path.join(root,name);if(fs.existsSync(src))fs.writeFileSync(path.join(out,name),await minHtml(fs.readFileSync(src,'utf8')))}
for(const name of ['style.css','lekh.css']){const src=path.join(root,'assets/css',name);if(fs.existsSync(src)){const css=new CleanCSS({level:2}).minify(fs.readFileSync(src,'utf8')).styles;fs.writeFileSync(path.join(out,'assets/css',name),css)}}
for(const name of ['main.js','lekh.js']){const src=path.join(root,'assets/js',name);if(fs.existsSync(src)){const js=fs.readFileSync(src,'utf8');const ob=JavaScriptObfuscator.obfuscate(js,{compact:true,controlFlowFlattening:true,deadCodeInjection:true,stringArray:true,stringArrayEncoding:['base64'],selfDefending:true}).getObfuscatedCode();fs.writeFileSync(path.join(out,'assets/js',name),ob)}}
if(fs.existsSync(path.join(root,'assets/favicon.svg')))fs.copyFileSync(path.join(root,'assets/favicon.svg'),path.join(out,'assets/favicon.svg'));
const postsDir=path.join(root,'content/posts'),published=[];if(fs.existsSync(postsDir)){for(const file of fs.readdirSync(postsDir).filter(f=>f.endsWith('.json'))){try{const p=JSON.parse(fs.readFileSync(path.join(postsDir,file),'utf8'));if(p.published===true&&p.title&&p.slug){published.push(p)}}catch(e){console.warn(`Skipping invalid post ${file}: ${e.message}`)}}}
published.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));const npDigits=s=>String(s).replace(/\d/g,d=>'०१२३४५६७८९'[d]);const dateLabel=d=>{if(!d)return'';const x=new Date(`${d}T00:00:00`);if(Number.isNaN(x.getTime()))return d;return npDigits(x.toLocaleDateString('en-CA',{year:'numeric',month:'short',day:'numeric'}))};
fs.mkdirSync(path.join(out,'data'),{recursive:true});fs.writeFileSync(path.join(out,'data/articles.json'),JSON.stringify(published.map(p=>({title:p.title,slug:p.slug,date:p.date,dateLabel:dateLabel(p.date),category:p.category||'',excerpt:p.excerpt||'',cover:p.cover||'',tags:p.tags||[],url:`lekh/${p.slug}.html`})),null,2));
const articleDir=path.join(out,'lekh');fs.mkdirSync(articleDir,{recursive:true});const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
for(const p of published){const seoTitle=p.seo_title||`${p.title} | बाबु निरोज`;const seoDesc=p.seo_description||p.excerpt||'';const tags=(p.tags||[]).map(t=>`<span>${esc(t)}</span>`).join('');const cover=p.cover?`<img class="article-cover" src="../${esc(String(p.cover).replace(/^\//,''))}" alt="${esc(p.title)}">`:'';const jsonLd=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:p.title,datePublished:p.date||undefined,author:{'@type':'Person',name:'बाबु निरोज'},description:seoDesc,image:p.cover||undefined});const html=`<!doctype html><html lang="ne"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(seoTitle)}</title><meta name="description" content="${esc(seoDesc)}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="article"><meta property="og:title" content="${esc(seoTitle)}"><meta property="og:description" content="${esc(seoDesc)}">${p.cover?`<meta property="og:image" content="../${esc(String(p.cover).replace(/^\//,''))}">`:''}<link rel="icon" href="../assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../assets/css/style.css"><link rel="stylesheet" href="../assets/css/lekh.css"><script type="application/ld+json">${jsonLd}</script></head><body><main class="lekh-main article-page"><a class="article-back" href="../lekh.html">← सबै लेख</a><article><header class="article-head"><span class="lekh-kicker">${esc(p.category||'लेख')}</span><h1>${esc(p.title)}</h1><div class="lekh-meta"><time>${esc(dateLabel(p.date))}</time></div><p class="article-excerpt">${esc(p.excerpt||'')}</p></header>${cover}<div class="article-body">${p.body||''}</div>${tags?`<div class="article-tags">${tags}</div>`:''}</article></main></body></html>`;fs.writeFileSync(path.join(articleDir,`${p.slug}.html`),await minHtml(html))}
for(const f of ['robots.txt','sitemap.xml'])fs.copyFileSync(path.join(root,f),path.join(out,f));console.log(`Production build created in dist/ (${published.length} published article(s))`);
